### ISSUE TITLE
replay isues on imx6

### ISSUE THREAD

**Issue by rdorsch** [kodi-pvr/pvr.hts#498]
Hi,

I am running the tvheadend client on a cubox-i with an iMX6 processor on LibreElec 10/Kodi 19.

Video replay with the tvheadend client does not work very well, in particular it seems, if there is motion, the image is not smooth. I use kodinerds-iptv as source.

If I put the same source in a *.strm file and play it with kodi directly, the replay is perfect.

I am wondering if the tvheadend client is using a different way to play the video than kodi itself.

Here are two kodi patches for iMX6 

https://github.com/LibreELEC/LibreELEC.tv/tree/master/projects/NXP/devices/iMX6/patches/kodi

I do not see anything suspicious in the kodi.log: http://ix.io/2SHi

Please let me know if any further information would be useful to understand the issue.

Thanks
Rainer

**Comment by rdorsch** [comment]
More debugging enabled:

http://ix.io/2SHr

**Comment by ksooo** [comment]
I'm pretty sure this is nothing that can be fixed in this addon.

**Comment by hagaygo** [comment]
It sounds like the problem i had on https://github.com/kodi-pvr/pvr.hts/issues/431.

if you can ,try the http streaming option added on https://github.com/kodi-pvr/pvr.hts/pull/471

**Comment by rdorsch** [comment]
@hagaygo Many thanks for your reply.

Changing to http streaming in the addon changes things. The video artefact goes away, but the video halts after a short while:

http://ix.io/2SMo

**Comment by ksooo** [comment]
As the addon only routes the data from tvheadend to kodi, without manipulating them, the issue needs to be either fixed in tvheadend  or kodi.

**Comment by rdorsch** [comment]
yes, but I just want to make sure that I have the correct settings in the addon. Does that look correct (tvheadend log):

```
2021-03-14 10:04:52.150 [   INFO] mpegts: kn-pipe-tv - phoenix in kodinerds-iptv - tuning on IPTV #1
2021-03-14 10:04:52.155 [   INFO] subscription: 0042: "HTTP" subscribing on channel "phoenix", weight: 100, adapter: "IPTV #1", network: "kodinerds-iptv", mux: "kn-pipe-tv - phoenix", provider: "IPTV-DE", service: "phoenix", profile="pass", hostname="192.168.7.32", username="tvh", client="Kodi/19.0 (X11; Linux armv7l) LibreELEC/10.0 App_Bitness/32 Version/19.0-(19.0.0)-Git:19.0-Matrix"
2021-03-14 10:04:52.155 [   INFO] spawn: Executing "/usr/bin/ffmpeg"

```

It seems if I switch to http streaming and not htsp, the replay improves to the same performance I see with the simple pvr client and putting it directly into the *.strm file.

Playing iptv steams still does not work perfectly (audio and video out of sync) on kodi, but this has really nothing todo with this addon.
